CREATE TABLE item (id SERIAL NOT NULL PRIMARY KEY,name_item VARCHAR(100) NOT NULL,price INT NOT NULL);
CREATE TABLE buyer (id SERIAL NOT NULL PRIMARY KEY,name_buyer VARCHAR(100) NOT NULL);
CREATE TABLE item_buyer (id SERIAL NOT NULL PRIMARY KEY,item_id INT NOT NULL REFERENCES item(id),buyer_id INT NOT NULL REFERENCES buyer(id));